// Generated by npm run types:db. Do not edit manually.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];
export type Database = {
  public: {
    Tables: {
      attachments: {
        Row: {
          id: string;
          household_id: string;
          uploaded_by: string;
          fault_id: string | null;
          complaint_id: string | null;
          debt_id: string | null;
          bucket: string;
          object_path: string;
          created_at: string;
          uploaded_at: string | null;
          upload_expires_at: string;
        };
        Insert: never;
        Update: never;
        Relationships: [];
      };
      audit_events: {
        Row: {
          id: string;
          household_id: string;
          actor_id: string;
          action: string;
          rule_id: string | null;
          proposal_id: string | null;
          exception_id: string | null;
          debt_id: string | null;
          payment_id: string | null;
          deletion_event_id: string | null;
          created_at: string;
          task_template_id: string | null;
          shower_slot_id: string | null;
        };
        Insert: never;
        Update: never;
        Relationships: [];
      };
      complaints: {
        Row: {
          id: string;
          household_id: string;
          author_id: string;
          target_id: string | null;
          title: string;
          description: string;
          created_at: string;
        };
        Insert: never;
        Update: never;
        Relationships: [];
      };
      debt_versions: {
        Row: {
          id: string;
          household_id: string;
          debt_id: string;
          version: number;
          total_cents: number;
          debt_cents: number;
          concept: string;
          occurred_on: string;
          recorded_by: string;
          correction_reason: string | null;
          created_at: string;
          creditor_id: string;
          debtor_id: string | null;
          payer_participates: boolean;
          products: string;
        };
        Insert: never;
        Update: never;
        Relationships: [];
      };
      debts: {
        Row: {
          id: string;
          household_id: string;
          created_by: string;
          creditor_id: string;
          debtor_id: string | null;
          kind: string;
          current_version: number;
          created_at: string;
        };
        Insert: never;
        Update: never;
        Relationships: [];
      };
      fault_comments: {
        Row: {
          id: string;
          household_id: string;
          fault_id: string;
          author_id: string;
          body: string;
          created_at: string;
        };
        Insert: never;
        Update: never;
        Relationships: [];
      };
      fault_deletion_events: {
        Row: {
          id: string;
          household_id: string;
          deleted_by: string;
          deleted_at: string;
        };
        Insert: never;
        Update: never;
        Relationships: [];
      };
      faults: {
        Row: {
          id: string;
          household_id: string;
          rule_version_id: string;
          reported_by: string;
          responsible_id: string;
          occurred_at: string;
          description: string;
          registered_at: string;
          maintained_by: string | null;
          maintained_at: string | null;
        };
        Insert: never;
        Update: never;
        Relationships: [];
      };
      households: {
        Row: {
          id: string;
          name: string;
          timezone: string;
          created_at: string;
        };
        Insert: never;
        Update: never;
        Relationships: [];
      };
      inventory_items: {
        Row: {
          id: string;
          household_id: string;
          scope: 'PERSONAL' | 'SHARED' | 'HOUSEHOLD';
          owner_id: string | null;
          created_by: string;
          name: string;
          quantity: number;
          unit: string;
          revision: number;
          created_at: string;
        };
        Insert: never;
        Update: never;
        Relationships: [];
      };
      members: {
        Row: {
          id: string;
          household_id: string;
          auth_user_id: string;
          role: 'ADMIN' | 'RESIDENT' | 'CONTROLLER';
          display_name: string;
          created_at: string;
        };
        Insert: never;
        Update: never;
        Relationships: [];
      };
      notifications: {
        Row: {
          id: string;
          household_id: string;
          recipient_id: string;
          report_id: string | null;
          exception_id: string | null;
          kind: string;
          read_at: string | null;
          created_at: string;
        };
        Insert: never;
        Update: never;
        Relationships: [];
      };
      payment_versions: {
        Row: {
          id: string;
          household_id: string;
          payment_id: string;
          version: number;
          amount_cents: number;
          recorded_by: string;
          occurred_on: string;
          correction_reason: string | null;
          created_at: string;
          debt_id: string;
        };
        Insert: never;
        Update: never;
        Relationships: [];
      };
      payments: {
        Row: {
          id: string;
          household_id: string;
          debt_id: string;
          created_by: string;
          current_version: number;
          created_at: string;
        };
        Insert: never;
        Update: never;
        Relationships: [];
      };
      report_entries: {
        Row: {
          id: string;
          household_id: string;
          report_id: string;
          fault_id: string | null;
          comment_id: string | null;
          complaint_id: string | null;
          deletion_event_id: string | null;
          task_id: string | null;
          debt_version_id: string | null;
          payment_version_id: string | null;
          shower_version_id: string | null;
          shopping_item_id: string | null;
        };
        Insert: never;
        Update: never;
        Relationships: [];
      };
      rule_proposals: {
        Row: {
          id: string;
          household_id: string;
          rule_id: string;
          base_version: number;
          title: string;
          category: string;
          description: string;
          reason: string;
          proposed_by: string;
          decided_by: string | null;
          result: 'APPROVED' | 'REJECTED' | null;
          created_at: string;
          decided_at: string | null;
        };
        Insert: never;
        Update: never;
        Relationships: [];
      };
      rule_versions: {
        Row: {
          id: string;
          household_id: string;
          rule_id: string;
          version: number;
          title: string;
          category: string;
          description: string;
          effective_at: string;
          created_by: string;
          approved_by: string | null;
          created_at: string;
        };
        Insert: never;
        Update: never;
        Relationships: [];
      };
      rules: {
        Row: {
          id: string;
          household_id: string;
          created_by: string;
          created_at: string;
          source_complaint_id: string | null;
        };
        Insert: never;
        Update: never;
        Relationships: [];
      };
      shopping_items: {
        Row: {
          id: string;
          household_id: string;
          scope: 'PERSONAL' | 'SHARED' | 'HOUSEHOLD';
          owner_id: string | null;
          created_by: string;
          name: string;
          quantity: number;
          unit: string;
          purchased_by: string | null;
          purchased_at: string | null;
          created_at: string;
        };
        Insert: never;
        Update: never;
        Relationships: [];
      };
      shower_slots: {
        Row: {
          id: string;
          household_id: string;
          created_by: string;
          resident_id: string;
          weekday: number;
          starts_at: string;
          ends_at: string;
          revision: number;
        };
        Insert: never;
        Update: never;
        Relationships: [];
      };
      shower_versions: {
        Row: {
          id: string;
          household_id: string;
          slot_id: string;
          resident_id: string;
          revision: number;
          weekday: number;
          starts_at: string;
          ends_at: string;
          created_at: string;
        };
        Insert: never;
        Update: never;
        Relationships: [];
      };
      task_occurrences: {
        Row: {
          id: string;
          household_id: string;
          template_id: string;
          assigned_to: string;
          due_date: string;
          due_time: string | null;
          completed_by: string | null;
          completed_at: string | null;
          created_at: string;
        };
        Insert: never;
        Update: never;
        Relationships: [];
      };
      task_templates: {
        Row: {
          id: string;
          household_id: string;
          created_by: string;
          initial_resident_id: string;
          title: string;
          description: string;
          zone: string;
          kind: string;
          anchor_date: string;
          interval_days: number;
          due_time: string | null;
          alternate: boolean;
          enabled: boolean;
          created_at: string;
        };
        Insert: never;
        Update: never;
        Relationships: [];
      };
      visit_exceptions: {
        Row: {
          id: string;
          household_id: string;
          requested_by: string;
          other_resident_id: string;
          controller_id: string;
          visitor: string;
          reason: string;
          kind: string;
          starts_at: string;
          ends_at: string;
          resident_decision: 'APPROVED' | 'REJECTED' | null;
          controller_decision: 'APPROVED' | 'REJECTED' | null;
          resident_decided_at: string | null;
          controller_decided_at: string | null;
          status: 'PENDING' | 'APPROVED' | 'REJECTED';
          created_at: string;
        };
        Insert: never;
        Update: never;
        Relationships: [];
      };
      weekly_reports: {
        Row: {
          id: string;
          household_id: string;
          starts_at: string;
          ends_at: string;
          generated_at: string;
        };
        Insert: never;
        Update: never;
        Relationships: [];
      };
    };
    Views: {
      current_payments: {
        Row: {
          id: string;
          household_id: string;
          current_version: number;
          created_at: string;
          debt_id: string;
          amount_cents: number;
          occurred_on: string;
          recorded_by: string;
        };
        Relationships: [];
      };
      current_rules: {
        Row: {
          id: string;
          household_id: string;
          rule_id: string;
          version: number;
          title: string;
          category: string;
          description: string;
          effective_at: string;
          created_by: string;
          approved_by: string | null;
          created_at: string;
        };
        Relationships: [];
      };
      debt_balances: {
        Row: {
          id: string;
          household_id: string;
          kind: string;
          creditor_id: string;
          debtor_id: string | null;
          current_version: number;
          concept: string;
          total_cents: number;
          debt_cents: number;
          paid_cents: number;
          pending_cents: number;
          occurred_on: string;
          payer_participates: boolean;
          products: string;
          created_at: string;
        };
        Relationships: [];
      };
      fault_history: {
        Row: {
          id: string;
          household_id: string;
          rule_version_id: string;
          reported_by: string;
          responsible_id: string;
          occurred_at: string;
          description: string;
          registered_at: string;
          maintained_by: string | null;
          maintained_at: string | null;
          rule_id: string;
          rule_title: string;
          category: string;
          photo_count: number;
        };
        Relationships: [];
      };
      latest_rules: {
        Row: {
          id: string;
          household_id: string;
          rule_id: string;
          version: number;
          title: string;
          category: string;
          description: string;
          effective_at: string;
          created_by: string;
          approved_by: string | null;
          created_at: string;
        };
        Relationships: [];
      };
      scheduled_tasks: {
        Row: {
          id: string;
          household_id: string;
          template_id: string;
          assigned_to: string;
          due_date: string;
          due_time: string | null;
          completed_by: string | null;
          completed_at: string | null;
          created_at: string;
          title: string;
          description: string;
          zone: string;
          kind: string;
          alternate: boolean;
        };
        Relationships: [];
      };
    };
    Functions: {
      add_inventory_item: {
        Args: {
          p_household: string | null;
          p_scope: 'PERSONAL' | 'SHARED' | 'HOUSEHOLD' | null;
          p_name: string | null;
          p_quantity: number | null;
          p_unit: string | null;
          p_request_id: string | null;
        };
        Returns: string;
      };
      add_shopping_item: {
        Args: {
          p_household: string | null;
          p_scope: 'PERSONAL' | 'SHARED' | 'HOUSEHOLD' | null;
          p_name: string | null;
          p_quantity: number | null;
          p_unit: string | null;
          p_request_id: string | null;
        };
        Returns: string;
      };
      buy_and_stock_item: {
        Args: {
          p_household: string | null;
          p_item: string | null;
          p_add_to_inventory: boolean | null;
        };
        Returns: undefined;
      };
      buy_shopping_item: {
        Args: { p_household: string | null; p_item: string | null };
        Returns: undefined;
      };
      cancel_invitation: {
        Args: { p_household: string | null; p_role: 'ADMIN' | 'RESIDENT' | 'CONTROLLER' | null };
        Returns: undefined;
      };
      claim_cleanup: { Args: { p_limit?: number | null }; Returns: Json[] };
      claim_membership: {
        Args: {
          p_auth_user: string | null;
          p_verified_email: string | null;
          p_name: string | null;
        };
        Returns: string;
      };
      claim_push_deliveries: {
        Args: { p_limit?: number | null };
        Returns: {
          id: string | null;
          lease_id: string | null;
          token: string | null;
          ticket_id: string | null;
          kind: string | null;
          notification_id: string | null;
          report_id: string | null;
          exception_id: string | null;
        }[];
      };
      cleanup_attachment_reservations: { Args: Record<string, never>; Returns: undefined };
      comment_fault: {
        Args: {
          p_household: string | null;
          p_fault: string | null;
          p_body: string | null;
          p_request_id: string | null;
        };
        Returns: string;
      };
      complete_task: {
        Args: { p_household: string | null; p_task: string | null };
        Returns: undefined;
      };
      create_rule: {
        Args: {
          p_household: string | null;
          p_title: string | null;
          p_category: string | null;
          p_description: string | null;
          p_effective_at: string | null;
          p_request_id: string | null;
          p_complaint_id?: string | null;
        };
        Returns: string;
      };
      create_shower_slot: {
        Args: {
          p_household: string | null;
          p_resident: string | null;
          p_weekday: number | null;
          p_start: string | null;
          p_end: string | null;
          p_request_id: string | null;
        };
        Returns: string;
      };
      create_task_template: {
        Args: {
          p_household: string | null;
          p_title: string | null;
          p_description: string | null;
          p_zone: string | null;
          p_kind: string | null;
          p_resident: string | null;
          p_anchor: string | null;
          p_interval_days: number | null;
          p_due_time: string | null;
          p_alternate: boolean | null;
          p_request_id: string | null;
        };
        Returns: string;
      };
      decide_rule_change: {
        Args: {
          p_household: string | null;
          p_proposal: string | null;
          p_decision: 'APPROVED' | 'REJECTED' | null;
        };
        Returns: undefined;
      };
      decide_visit_exception: {
        Args: {
          p_household: string | null;
          p_exception: string | null;
          p_decision: 'APPROVED' | 'REJECTED' | null;
        };
        Returns: 'PENDING' | 'APPROVED' | 'REJECTED';
      };
      delete_account: {
        Args: {
          p_household: string | null;
          p_member: string | null;
          p_confirmation: string | null;
        };
        Returns: Json;
      };
      delete_fault: {
        Args: { p_household: string | null; p_fault: string | null; p_request_id: string | null };
        Returns: string;
      };
      edit_shower_slot: {
        Args: {
          p_household: string | null;
          p_slot: string | null;
          p_resident: string | null;
          p_weekday: number | null;
          p_start: string | null;
          p_end: string | null;
          p_expected_revision: number | null;
        };
        Returns: undefined;
      };
      fault_monthly: {
        Args: { p_household: string | null; p_before?: string | null };
        Returns: { month: string | null; responsible_id: string | null; total: number | null }[];
      };
      fault_statistics: {
        Args: { p_household: string | null; p_period?: string | null };
        Returns: { responsible_id: string | null; category: string | null; total: number | null }[];
      };
      finish_attachment: {
        Args: { p_household: string | null; p_attachment: string | null };
        Returns: undefined;
      };
      finish_cleanup: {
        Args: { p_id: string | null; p_lease: string | null; p_success: boolean | null };
        Returns: undefined;
      };
      finish_push_delivery: {
        Args: {
          p_id: string | null;
          p_lease: string | null;
          p_result: string | null;
          p_ticket?: string | null;
        };
        Returns: undefined;
      };
      generate_weekly_report: {
        Args: { p_household: string | null; p_end: string | null };
        Returns: string;
      };
      get_session: {
        Args: Record<string, never>;
        Returns: {
          member_id: string | null;
          household_id: string | null;
          role: 'ADMIN' | 'RESIDENT' | 'CONTROLLER' | null;
          display_name: string | null;
        }[];
      };
      invite_replacement: {
        Args: {
          p_household: string | null;
          p_email: string | null;
          p_role: 'ADMIN' | 'RESIDENT' | 'CONTROLLER' | null;
        };
        Returns: undefined;
      };
      list_invitations: {
        Args: { p_household: string | null };
        Returns: { email: string | null; role: 'ADMIN' | 'RESIDENT' | 'CONTROLLER' | null }[];
      };
      maintain_fault: {
        Args: { p_household: string | null; p_fault: string | null };
        Returns: undefined;
      };
      mark_notification_read: {
        Args: { p_household: string | null; p_notification: string | null };
        Returns: undefined;
      };
      materialize_tasks: {
        Args: { p_household: string | null; p_through: string | null };
        Returns: number;
      };
      money_summary: {
        Args: { p_household: string | null; p_report?: string | null };
        Returns: { member_id: string | null; balance_cents: number | null }[];
      };
      propose_rule_change: {
        Args: {
          p_household: string | null;
          p_rule: string | null;
          p_title: string | null;
          p_category: string | null;
          p_description: string | null;
          p_reason: string | null;
          p_request_id: string | null;
          p_expected_version: number | null;
        };
        Returns: string;
      };
      refresh_calendar: { Args: { p_household: string | null }; Returns: number };
      register_complaint: {
        Args: {
          p_household: string | null;
          p_target: string | null;
          p_title: string | null;
          p_description: string | null;
          p_request_id: string | null;
        };
        Returns: string;
      };
      register_fault: {
        Args: {
          p_household: string | null;
          p_responsible: string | null;
          p_rule: string | null;
          p_occurred_at: string | null;
          p_description: string | null;
          p_request_id: string | null;
        };
        Returns: string;
      };
      register_push_token: {
        Args: { p_household: string | null; p_token: string | null };
        Returns: undefined;
      };
      rename_household: {
        Args: { p_household: string | null; p_name: string | null };
        Returns: undefined;
      };
      request_visit_exception: {
        Args: {
          p_household: string | null;
          p_visitor: string | null;
          p_reason: string | null;
          p_kind: string | null;
          p_starts_at: string | null;
          p_ends_at: string | null;
          p_request_id: string | null;
        };
        Returns: string;
      };
      reserve_attachment: {
        Args: {
          p_household: string | null;
          p_kind: string | null;
          p_record: string | null;
          p_request_id: string | null;
        };
        Returns: string;
      };
      run_maintenance: { Args: Record<string, never>; Returns: number };
      save_debt: {
        Args: {
          p_household: string | null;
          p_kind: string | null;
          p_creditor: string | null;
          p_debtor: string | null;
          p_total_cents: number | null;
          p_concept: string | null;
          p_occurred_on: string | null;
          p_request_id: string | null;
          p_debt_id?: string | null;
          p_expected_version?: number | null;
          p_reason?: string | null;
        };
        Returns: string;
      };
      save_expense: {
        Args: {
          p_household: string | null;
          p_payer: string | null;
          p_participants: string[] | null;
          p_total_cents: number | null;
          p_concept: string | null;
          p_occurred_on: string | null;
          p_products: string | null;
          p_request_id: string | null;
          p_expense_id?: string | null;
          p_expected_version?: number | null;
          p_reason?: string | null;
        };
        Returns: string;
      };
      save_payment: {
        Args: {
          p_household: string | null;
          p_debt_id: string | null;
          p_amount_cents: number | null;
          p_occurred_on: string | null;
          p_request_id: string | null;
          p_payment_id?: string | null;
          p_expected_version?: number | null;
          p_reason?: string | null;
        };
        Returns: string;
      };
      set_inventory_quantity: {
        Args: {
          p_household: string | null;
          p_item: string | null;
          p_quantity: number | null;
          p_expected_revision: number | null;
        };
        Returns: number;
      };
      set_task_enabled: {
        Args: { p_household: string | null; p_template: string | null; p_enabled: boolean | null };
        Returns: undefined;
      };
      swap_shower_slots: {
        Args: {
          p_household: string | null;
          p_first: string | null;
          p_second: string | null;
          p_first_revision: number | null;
          p_second_revision: number | null;
        };
        Returns: undefined;
      };
      unregister_push_token: {
        Args: { p_household: string | null; p_token: string | null };
        Returns: undefined;
      };
    };
    Enums: {
      member_role: 'ADMIN' | 'RESIDENT' | 'CONTROLLER';
      inventory_scope: 'PERSONAL' | 'SHARED' | 'HOUSEHOLD';
      decision: 'APPROVED' | 'REJECTED';
      exception_status: 'PENDING' | 'APPROVED' | 'REJECTED';
    };
    CompositeTypes: Record<string, never>;
  };
};
export type Relation = keyof Database['public']['Tables'] | keyof Database['public']['Views'];
export type Row<T extends Relation> = (Database['public']['Tables'] &
  Database['public']['Views'])[T]['Row'];
